config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :tasks do
    resources :comments, only: %i[index new create]
  end
  resources :task_reports, only: [:index]


  resources :profiles, only: %i[show new create update edit] do
    get 'private_page', on: :member
    post 'change_privacy', on: :member
    resources :comments, only: %i[index]
  end

  resources :pluses, only: %i[create destroy]
  resources :minuses, only: %i[create destroy]
end

app/models/task.rb
class Task < ApplicationRecord
  enum priority: {low: 0, medium: 10, high: 20}
  enum status: {incomplete: 0, complete: 10}

  validates :title, length: {minimum: 4}
  validates :title, length: {maximum: 20}
  validates :description, presence: true 
  validates :description, length: {maximum: 280} 

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create destroy search]
  before_action :user_profile?
  before_action :find_task, only: %i[edit update show confirm_delete destroy delete_comment]
  skip_before_action :verify_authenticity_token, only: %i[search]
    
  def index
    @tasks = Task.all.where(user_id: current_user.id).order(id: :desc)
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save
      redirect_to tasks_path, notice: 'Task was successfully created!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: 'Task was successfully updated!'
    else
      redirect_to tasks_path, notice: 'Task wasn\'t updated!'
    end
  end

  def destroy
    puts @task
    @task.destroy
    redirect_to tasks_path
  end

  def complete
    # This parameter is handled on edit form since when it's created by default is "incomplete"
  end

  def incomplete
    # This parameter is handled on edit form since when it's created by default is "incomplete"
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :priority, :status, :share)
  end  

  def comment_params
    # comments are are been treated on comments controller
    # params.require(:comment).permit(:body, :like_status)
  end 

  def sanitize_sql_like(string, escape_character = "\\")
    pattern = Regexp.union(escape_character, "%", "_")
    string.gsub(pattern) { |x| [escape_character, x].join }
  end
end

app/views/tasks/edit.html.erb
<div class='form-group align-item-center container border' >
  <div class='text-center'>
    <h1>Edit Task </h1>
  </div>
  
  <%= form_for @task do |f| %>
    <div class='row'>  
      <p class='col-4'></p>
      <div class='col-4 text-center' >
        <%= f.label :title, 'Title:' %>
        <%= f.text_field :title, class: 'form-control mb-2', placeholder: 'Type a title'%>
      </div>
    </div>
    <br> 
        
    <div class='row'>
      <p class='col-4'></p> 
      <div class='col-4' align='center'>
        <%= f.label :description, 'Description'%>
        <%= f.text_area :description, class: 'form-control mb-2', rows: '4'%>
      </div> 
    </div>

    <br>

    <div class='row'>
      <p class='col-4'></p> 
      <div class='col-4' align='center'>
        <%= f.label :priority, 'Priority', placeholder: 'low, medium or high' %>
        <%= f.text_area :priority, class: 'form-control mb-2', rows: '4' %>
      </div>
    </div>

    <br>

    <div class='row'>
      <p class='col-4'></p> 
      <div class='col-4' align='center'>
        <%= f.label :status, 'Status', placeholder: 'Complete or Inconplete' %>
        <%= f.text_area :status, class: 'form-control mb-2', rows: '4' %>
      </div>
    </div>

    <br>

    <div class='row'>
      <p class='col-4'></p> 
      <div class='col-4' align='center'> 
        <%= f.hidden_field :user_id, value: params[:id]%>
        <%= f.submit class: 'btn btn-primary col-4'%>
        <%= link_to 'Go Back', :back, class: 'btn btn-secondary col-4' %>
      </div>
    </div>

  <% end %>
</div>

app/views/tasks/index.html.erb
<div class='text-center'>
  <h1>My Tasks</h1>
</div>

<br>

<div class="d-flex container justify-content-center">
  <table>
    <thead>
      <tr>
        <th>Created at</th>
        <th>Tasks (ID)</th>
        <th>Title</th>
        <th>Description</th>
        <th>Priority</th>
        <th>Status</th>
        <th>User nickname</th>
        <th>Handle</th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= time_ago_in_words(task.created_at) %></td>
          <td><%= task.id %></td>
          <td><%=link_to "#{task.title}", task_path(task) %></td>      
          <td><%=task.description %></td>
          <td><%=task.priority %></td>
          <td><%=task.status %></td>
          <td><%=task.user.profile.nickname %></td>
          <td>
          <div class="d-flex flex-row m-2">
            <%= link_to '', edit_task_path(task), class: 'fa fa-edit mr-1' %> 
            <%= link_to '', task, class: 'fa fa-trash ml-1 mr-1', method: :delete, data: { confirm: 'Are you sure?' } %> 
            <%= link_to '', new_task_comment_path(task), class: 'fa fa-comment ml-1' %>
          </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/new.html.erb
<div class='form-group align-item-center container border' >
  <div class='text-center'>
    <h1>New Task</h1>
  </div>
  
  <%= form_for @task do |f| %>
    <div class='row'>  
      <p class='col-4'></p>
      <div class='col-4 text-center'>
        <%= f.label :title, 'Title:' %>
        <%= f.text_field :title, class: 'form-control mb-2', placeholder: 'Type a title'%>
      </div>
    </div>
    <br> 
  
    <div class='row'>
      <p class='col-4'></p> 
      <div class='col-4' align='center'>
        <%= f.label :description, 'Description'%>
        <%= f.text_area :description, class: 'form-control mb-2', rows: '4'%>
      </div> 
    </div>

    <br>

    <div class='row'>
      <p class='col-4'></p> 
      <div class='col-4' align='center'>
        <%= f.label :priority, 'Priority', placeholder: 'low, medium or high' %>
        <%= f.text_area :priority, class: 'form-control mb-2', rows: '4' %>
      </div>
    </div>

    <br>

    <div class='row'>
      <p class='col-4'></p> 
      <div class='col-4' align='center'> 
        <%= f.hidden_field :user_id, value: params[:id]%>
        <%= f.submit class: 'btn btn-primary col-4'%>
        <%= link_to 'Go Back', :back, class: 'btn btn-secondary col-4' %>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/show.html.erb
<h4 class="text-center"> Task id: <%= @task.id %> </h4>
<div class='d-flex container justify-content-center' >
  <table>
    <thead>
      <tr>
        <th>Created at</th>
        <th>Title</th>
        <th>Description</th>
        <th>Priority</th>
        <th>Status</th>
        <th>User nickname</th>
        <th>Handle</th>
      </tr>
    </thead>
    
    <tbody>
      <tr>
        <td><%= time_ago_in_words(@task.created_at) %></td>
        <td><%=@task.title %></td>      
        <td><%=@task.description %></td>
        <td><%=@task.priority %></td>
        <td><%=@task.status %></td>
        <td><%=@task.user.profile.nickname %></td>
        <td>
        <div class="d-flex flex-row m-2">
          <%= link_to '', edit_task_path(@task), class: 'fa fa-edit mr-1' %> 
          <%= link_to '', @task, class: 'fa fa-trash ml-1 mr-1', method: :delete, data: { confirm: 'Are you sure?' } %> 
          <%= link_to '', new_task_comment_path(@task), class: 'fa fa-comment ml-1' %>
        </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<br>

<div class='d-flex justify-content-center'> 
  <%= link_to 'Go Back', :back, class: 'btn btn-secondary col-2' %>
</div>